### ISSUE TITLE
clone 下来后 按着步骤执行 npm run server 报错了

### ISSUE THREAD

**Issue by gggso** [chachaxw/vue-element-quick-start#1]
sh: supervisor: command not found

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! vue-element-quick-start@1.0.0 server: `supervisor node server/server.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the vue-element-quick-start@1.0.0 server script 'supervisor node server/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-element-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     supervisor node server/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-element-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-element-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /wwwroot/vue-element-quick-start/server/npm-debug.log

**Comment by chachaxw** [comment]
supervisor: command not found
你没有安装supervisor 这个命令行工具，我默认启动的时候，用supervisor 启动的

**Comment by gggso** [comment]
谢谢
