### ISSUE TITLE
为什么我在mac上正常，到windows下就报错了

### ISSUE THREAD

**Issue by jasonzhao588** [chachaxw/vue-element-quick-start#6]
npm run dev

> vue-element-quick-start@1.0.0 dev E:\Works\law
> node build/dev-server.js

 ERROR  Failed to compile with 11 errors                                                                                  11:42:01

 error  in ./src/main.js

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  E:\Works\law\src\main.js:1:24
  import 'normalize.css';
                          ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  E:\Works\law\src\main.js:2:49
  import 'element-ui/lib/theme-default/index.css';
                                                   ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  E:\Works\law\src\main.js:3:23
  import Vue from 'vue';
                         ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  E:\Works\law\src\main.js:4:25
  import Vuex from 'vuex';
                           ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  E:\Works\law\src\main.js:5:36
  import VueRouter from 'vue-router';
                                      ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  E:\Works\law\src\main.js:6:34
  import Element from 'element-ui';
                                    ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  E:\Works\law\src\main.js:7:29
  import App from './App.vue';
                               ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  E:\Works\law\src\main.js:8:35
  import store from './store/store';
                                     ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  E:\Works\law\src\main.js:9:31
  import routes from './routes';
                                 ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  E:\Works\law\src\main.js:10:1

   ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  E:\Works\law\src\main.js:11:18
  Vue.use(Element);
                    ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  E:\Works\law\src\main.js:12:20
  Vue.use(VueRouter);
                      ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  E:\Works\law\src\main.js:13:15
  Vue.use(Vuex);
                 ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  E:\Works\law\src\main.js:14:29
  // Vue.config.silent = true;
                               ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  E:\Works\law\src\main.js:15:1

   ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  E:\Works\law\src\main.js:16:31
  const router = new VueRouter({
                                 ^

**Comment by chachaxw** [comment]
eslint 代码规范问题，可以点击报错提示的链接去看详细的规则。
